### ISSUE TITLE
Exception while indexing versions: Invalid request body

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/gov_backup#95]
Error logged as:
`status:exception job:objects.index action:process item_id:64,081,957 exception:Invalid request body provided timestamp:June 18th 2018, 16:25:13.000 _id:AWQUyZa_LVl3nVHbChyI _type:jobs _index:open_scrapers_log _score: -`

Object:
```
   'dataset' => 'web_objects_versions',
   'object_id' => '248471',
```

DATA TO INDEX:
```
array (
  'index' => 'mojepanstwo_v1',
  'type' => 'objects',
  'id' => '64081957',
  'body' => 
  array (
    'id' => '248471',
    'dataset' => 'web_objects_versions',
    'data' => 
    array (
      'web_objects_versions' => 
      array (
        'body_hash' => '2c376303078b27ac4211b882c83acc5c',
        'body_transformed' => '1',
        'http_code' => '200',
        'id' => '248471',
        'object_id' => '282467',
        'type' => '1',
        'media_type' => 'text/html',
        'content_length_bytes' => NULL,
        'size_bytes' => '37860',
        'title' => 'Заключительный отчёт по вопросу об установлении обстоятельств и причин катастрофы самолёта TУ-154M, борт 101 под Смоленском | Kancelaria Prezesa Rady Ministrów',
        'description' => NULL,
        'image_url' => NULL,
        'image_object_id' => NULL,
        'locale' => 'en',
        'site_name' => NULL,
        'keywords' => NULL,
        'has_body_text' => '0',
        'first_seen_date' => '2018-05-10T01:43:31',
        'last_seen_date' => '2018-05-10T01:43:31',
        'url' => 'www.premier.gov.pl/en/news/aktualnosci/zaklyuchitelnyy-otchyot-po-voprosu-ob-ustanovlenii-obstoyatelstv-i-prichin.html',
      ),
    ),
    'title' => 'Заключительный отчёт по вопросу об установлении обстоятельств и причин катастрофы самолёта TУ-154M, борт 101 под Смоленском | Kancelaria Prezesa Rady Ministrów',
    'slug' => 'Заключительный-отчёт-по-вопросу-об-установлении-обстоятельств-и-при�',
    'date' => '2018-05-10T01:43:31',
    'text' => '',
    'acronym' => NULL,
    'location' => NULL,
    'adres' => NULL,
    'weights' => 
    array (
      'main' => 
      array (
        'enabled' => false,
        'score' => 0,
      ),
    ),
    'alerts' => 
    array (
    ),
    'contexts' => 
    array (
    ),
    'feeds' => 
    array (
    ),
    'feeds_channels' => 
    array (
    ),
    'feed_dataset_order' => 
    array (
    ),
    'subs' => 
    array (
    ),
    '_portals' => 
    array (
    ),
  ),
)
```

Full stack trace below, originating in our code at 
https://github.com/epforgpl/OpenScrapers/blob/4e7b9c0f5a784c8c9ea4eb36096f0a0916342e47/src/Epf/ObjectsBundle/Jobs/Index.php#L276

```
*** Exception: Invalid request body provided
## /home/mp/openscrapers/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(289)
#0 /home/mp/openscrapers/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(248): GuzzleHttp\Ring\Client\CurlFactory->addStreamingBody(Array, Array)
#1 /home/mp/openscrapers/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(203): GuzzleHttp\Ring\Client\CurlFactory->applyBody(Array, Array)
#2 /home/mp/openscrapers/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(30): GuzzleHttp\Ring\Client\CurlFactory->applyMethod(Array, Array)
#3 /home/mp/openscrapers/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(84): GuzzleHttp\Ring\Client\CurlFactory->__invoke(Array, Resource id #587)
#4 /home/mp/openscrapers/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(68): GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray(Array)
#5 /home/mp/openscrapers/vendor/guzzlehttp/ringphp/src/Client/Middleware.php(30): GuzzleHttp\Ring\Client\CurlHandler->__invoke(Array)
#6 /home/mp/openscrapers/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(196): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}(Array)
#7 /home/mp/openscrapers/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(171): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#8 /home/mp/openscrapers/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(106): Elasticsearch\Connections\Connection->performRequest('PUT', '/mojepanstwo_v1...', Array, false, Array, Object(Elasticsearch\Transport))
#9 /home/mp/openscrapers/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1578): Elasticsearch\Transport->performRequest('PUT', '/mojepanstwo_v1...', Array, Array, Array)
#10 /home/mp/openscrapers/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(791): Elasticsearch\Client->performRequest(Object(Elasticsearch\Endpoints\Index))
#11 /home/mp/openscrapers/src/Epf/ObjectsBundle/Jobs/Index.php(276): Elasticsearch\Client->index(Array)
#12 /home/mp/openscrapers/src/AppBundle/Jobs/JobsFromQueueManager.php(142): Epf\ObjectsBundle\Jobs\Index->doProcess('64081957')
#13 /home/mp/openscrapers/src/AppBundle/Jobs/JobsFromQueueManager.php(130): AppBundle\Jobs\JobsFromQueueManager->processAfterLocking('64081957')
#14 /home/mp/openscrapers/src/AppBundle/Command/JobsProcessCommand.php(32): AppBundle\Jobs\JobsFromQueueManager->process('64081957')
#15 /home/mp/openscrapers/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(264): AppBundle\Command\JobsProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/mp/openscrapers/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(859): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/mp/openscrapers/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(206): Symfony\Component\Console\Application->doRunCommand(Object(AppBundle\Command\JobsProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/mp/openscrapers/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(81): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/mp/openscrapers/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(125): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/mp/openscrapers/bin/console(28): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#21 {main}
```

**Comment by KrzysztofMadejski** [comment]
Issue:
- in `\Elasticsearch\Connections\performRequest` the line `$body = $this->serializer->serialize($body);` returns `false` .. khem khem
- `json_encode($data, JSON_PRESERVE_ZERO_FRACTION)` return false
- after deleting problematic slug the json was properly encoded

So the real issue is #184
